# Generated by Django 3.0.6 on 2020-07-25 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('where', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('wait', models.IntegerField()),
                ('work', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('info', models.TextField()),
                ('prof_pic', models.ImageField(upload_to='image_upload')),
                ('choice', models.CharField(max_length=80)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_requests_created', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
